routes/web.php
Route::middleware(['web', 'auth'])->prefix('/admin')->namespace('Admin')->group(function () {

    Route::get('/', 'HomeController@index')->name('dashboard');

     /*
     |--------------------------------------------------------------------------
     | Web  Roles & Permissions routes
     |--------------------------------------------------------------------------
     */
    Route::resource('permissions', 'PermissionsController');
    Route::post('permissions_mass_destroy', 'PermissionsController@massDestroy')->name('permissions.mass_destroy');
    Route::resource('roles', 'RolesController');
    Route::post('roles_mass_destroy', 'RolesController@massDestroy')->name('roles.mass_destroy');

    /*
    |--------------------------------------------------------------------------
    | Web  User Manager routes
    |--------------------------------------------------------------------------
    */
    Route::resource('users', 'UsersController');
    Route::post('users_mass_destroy', 'UsersController@massDestroy')->name('users.mass_destroy');

    /*
    |--------------------------------------------------------------------------
    | Web  Upload routes
    |--------------------------------------------------------------------------
    */
    //Route::resource('fileuploads','UploadController');

    Route::get('upload/tickets', 'UploadTicketsController@show')->name('upload.tickets');
    Route::post('upload/tickets/store', 'UploadTicketsController@store')->name('upload.tickets.store');
    Route::get('upload/tickets/process', 'UploadTicketsController@process')->name('upload.tickets.process');

    Route::post('upload/historic/store','UploadHistoricController@store')->name('upload.historic.store');

    Route::post('upload/reconcile/store', 'UploadReconcileController@store')->name('upload.reconcile.store');
    Route::get('upload/reconcile/process', 'UploadReconcileController@process')->name('upload.reconcile.process');

    Route::post('upload/payments/store', 'UploadPaymentsController@store')->name('upload.payments.store');
    Route::get('upload/payments/process', 'UploadPaymentsController@process')->name('upload.payments.process');

    Route::get('upload/users', 'UploadUsersController@show')->name('upload.users');
    Route::post('upload/users/store', 'UploadUsersController@store')->name('upload.users.store');
    Route::get('upload/users/process', 'UploadUsersController@process')->name('upload.users.process');

    Route::get('upload/expenses', 'UploadExpensesController@show')->name('upload.expenses');
    Route::post('upload/expenses/store', 'UploadExpensesController@store')->name('upload.expenses.store');
    Route::get('upload/expenses/process', 'UploadExpensesController@process')->name('upload.expenses.process');

    Route::get('upload/business-expenses', 'UploadBusinessExpensesController@show')->name('upload.business-expenses');
    Route::post('upload/business-expenses/store', 'UploadBusinessExpensesController@store')->name('upload.business-expenses.store');
    Route::get('upload/business-expenses/process', 'UploadBusinessExpensesController@process')->name('upload.business-expenses.process');

    Route::delete('upload', 'UploadController@destroy')->name('upload.destroy');

    /*
    |--------------------------------------------------------------------------
    | Web platform users routes
    |--------------------------------------------------------------------------
    */
    Route::get('platform-users','PlatformUserController@index')->name('platform-users');
    Route::get('platform-users/{id}','PlatformUserController@show')->name('platform-users.show');
    Route::put('platform-users/{id}','PlatformUserController@update')->name('platform-users.update');
    Route::delete('platform-users/{id}','PlatformUserController@delete')->name('platform-users.delete');

     /*
    |--------------------------------------------------------------------------
    | Web  Ticket Management/Inventory routes
    |--------------------------------------------------------------------------
    */

    Route::post('tickets/all/datatable', 'TicketController@ticketsAllDatatable');
    Route::get('tickets/all','TicketController@ticketsAll')->name('tickets.all');

    /*
    |--------------------------------------------------------------------------
    | Web  transfer routes
    |--------------------------------------------------------------------------
    */

    Route::get('transfer', 'TransferController@index')->name('transfer');
    Route::post('transfer/updateUserCode/{id}', 'TransferController@updateUserCode')->name('transfer.updateUserCode');

    /*
    |--------------------------------------------------------------------------
    | Web  Ticket Management/Inventory routes
    |--------------------------------------------------------------------------
    */

    Route::post('inventory/datatable', 'TicketController@datatable');
    Route::put('tickets/updatebatch/{id}', 'TicketController@updateBatch')->name('tickets.update_batch');
    Route::post('tickets/splitbatch/{id}', 'TicketController@splitBatch')->name('tickets.split_batch');
    Route::get('tickets/returntostock/{id}', 'TicketController@returnToStock');
    Route::get('tickets/inventoryinhand/{id}/{status}', 'TicketController@inventoryInHand');
    Route::get('/tickets/ticketsinhand/{id}/{status}', 'TicketController@ticketsInHand');
    Route::get('/tickets/handling/{id}/{status}', 'TicketController@handling');
    //Route::resource('tickets','InventoryController');
    Route::post('ticket/refund-to/{id}', 'TicketController@refundTo')->name('ticket.refundTo');

    /*
    |--------------------------------------------------------------------------
    | Web  Ticket Not Received routes
    |--------------------------------------------------------------------------
    */

    Route::get('ticket-not-received/{ticketType}', 'TicketNotReceivedController@index')->name('ticket-not-received.index');

    /*
    |--------------------------------------------------------------------------
    |Fulfillment board routes
    |--------------------------------------------------------------------------
    */
    Route::get('fulfillment-board', 'FulfillmentBoardController@index')->name('fulfillment-board.index');
    Route::post('fulfillment-board/datatable', 'FulfillmentBoardController@datatable');
    Route::get('fulfillment-board/inventory-quantities/{inventoryQuantitiesIds}', 'FulfillmentBoardController@inventoryQuantities');
    Route::post('fulfillment-board/export', 'FulfillmentBoardController@export')->name('fulfillment-board.export');
    Route::post('fulfillment-board/import', 'FulfillmentBoardController@import')->name('fulfillment-board.import');
    Route::post('fulfillment-board/updateMass', 'FulfillmentBoardController@updateMass')->name('fulfillment-board.updateMass');
    Route::post('fulfillment-board/massTicketsInHand', 'FulfillmentBoardController@massTicketsInHand')->name('fulfillment-board.massTicketsInHand');
    Route::resource('fulfillment-board', 'FulfillmentBoardController');

    /*
    |--------------------------------------------------------------------------
    | Web Fulfillment routes
    |--------------------------------------------------------------------------
    */
    Route::get('fulfillment/{ticketType}', 'FulfillmentController@index')->name('fulfillment.index');

    /*
    |--------------------------------------------------------------------------
    | Web  Ticket Management/Delivered routes
    |--------------------------------------------------------------------------
    */

    Route::post('delivered/datatable', 'DeliveredController@datatable');
    Route::get('delivered/toDelivered/{id}', 'DeliveredController@deliveredTicket')->name('delivered.deliveredTicket');
    Route::resource('delivered','DeliveredController');

    /*
    |--------------------------------------------------------------------------
    | Web  Ticket Management/Completed routes
    |--------------------------------------------------------------------------
    */

    Route::post('completed/datatable', 'CompletedController@datatable');
    Route::get('completed/toCompleted/{id}', 'CompletedController@completedTicket')->name('completed.completedTicket');
    Route::resource('completed','CompletedController');

    /*
    |--------------------------------------------------------------------------
    | Web  Ticket SOLD   YES - IN HAND YES  routes
    |--------------------------------------------------------------------------
    */

    Route::get('tickets/toDetails/{id}', 'InventoryController@detailsTicket')->name('tickets.detailsTicket');
    Route::resource('tickets','InventoryController');
    //Route::post('tickets/splittickets/{id}', 'InventoryController@splitTickets')->name('tickets.split_tickets');
    //Route::get('ticketInfo/sold/returntostock/{id}', 'InventoryController@returnTicketToStock');
    Route::post('tickets/handlingMass', 'InventoryController@handlingMass')->name('tickets.handlingMass');
    Route::post('tickets/changeInHandMass', 'InventoryController@changeInHandMass')->name('tickets.changeInHandMass');

    /*
     *
    |--------------------------------------------------------------------------
    | Web  purchases routes
    |--------------------------------------------------------------------------
    */
    Route::post('purchases/datatable', 'PurchasesController@datatable');
    Route::resource('purchases', 'PurchasesController');
    Route::post('purchases/update/{id}', 'PurchasesController@update')->name('purchases.update');
    Route::post('purchases/updateBuyerInfo/{purchase_number}', 'PurchasesController@updateBuyerInfo')->name('purchases.updateBuyerInfo');
    Route::post('purchases/reconcile', 'PurchasesController@reconcileMass')->name('purchases.reconcileMass');

    /*
     *
    |--------------------------------------------------------------------------
    | Web  Adjustments routes

app/Models/Card.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;

class Card extends Model
{
    protected $table = 'cards';

    /**
     *
     */
    public static function getByName($name)
    {
    	return self::where('name', $name)->first();
    }
    
}

app/Models/PlatformUser.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Str;
use Laravel\Sanctum\HasApiTokens;

class PlatformUser extends Authenticatable
{
	use HasApiTokens, Notifiable;
	
    protected $table = 'platform_users';

    protected $fillable = [
    	'unique_id',
        'first_name',
        'last_name',
        'email_1',
        'email_2',
        'date_of_birth',
        'address_line_1',
        'address_line_2',
        'address_city',
        'address_state',
        'address_zip',
        'country',
        'phone',
        'referral_1',
        'referral_2',
        'desired_events',
		'presale_information',
        'events_alert_service',
        'express_transfer_service',
        'weekly_updates',
        'weekly_portfolio',
        'whatsapp_alerts',
        'share_desired_events',
        'permission_to_contact',
        'tcs_company_policies',
        'portfolio_needed',
        'browser',
        'ip_address',
        'location',
        'user_code',
		'blocked',
		'registered_at',
        'filled_at',
		'left_at',
		'password',
	];

	protected $hidden = [
		'password'
	];

	protected $casts = [
		'date_of_birth'  => 'date',
		'desired_events' => 'array',
		'location'       => 'array',
		'registered_at'  => 'datetime',
		'filled_at'      => 'date',
		'left_at'        => 'date',
		'portfolio_needed'=> 'boolean',
	];

	/**
	 * @return string
	 */
	public static function generatePassword()
	{
		return Str::random(8);
	}

	/**
	 * 
	 */
	public function payments()
	{
		return $this->hasMany(Payment::class, 'user_id');
	}

	/**
	 * 
	 */
	public function rebates()
	{
		return $this->hasMany(Rebate::class, 'buyer', 'user_code');
	}

	/**
	 * 
	 */
	public function rebatesWithoutNotifications()
	{
		return $this->rebates()->whereNull('notified_at')->orderBy('sold_date', 'desc');
	}

	/**
	 *
	 */
	public function getChunkedRebatesWithoutNotifications()
	{
		$chunks = collect();
		$this->rebatesWithoutNotifications->each(function($rebate) use (&$chunks) {
			if ($chunks->count() == 0 || $chunks->last()->sum('total_rebate') >= config('tt.low_rebate_notify_limit')) {
				$chunks->push(collect());
			}
			$chunks->last()->push($rebate);
		});

		return $chunks;
	}

	/**
	 * 
	 */
	public function fcmClientTokens()
	{
		return $this->hasMany(FcmClientToken::class);
	}

	/**
	 *
	 */
	public function getFullNameAttribute()
	{
		return $this->first_name . ' ' . $this->last_name;
	}

	/**
	 *
	 */
	public function getFullNameWithCodeAttribute()
	{
		return $this->full_name . ' (' . $this->user_code . ')';
	}

	/**
	 *
	 */
	public function getEmailsAttribute()
	{
		$emails = collect();
		if ($this->email_1) {
			$emails->push($this->email_1);
		}
		if ($this->email_2) {
			$emails->push($this->email_2);
		}
		return $emails;
	}

	/**
	 *
	 */
	public function getFullAddressAttribute()
	{
		$address = collect();
		if ($this->address_line_1) {
			$address->push(trim($this->address_line_1));
		}
		if ($this->address_line_2) {
			$address->push(trim($this->address_line_2));
		}
		if ($this->address_city) {
			$address->push(trim($this->address_city));
		}
		if ($this->address_state) {
			$address->push(trim($this->address_state));
		}
		if ($this->address_zip) {
			$address->push(trim($this->address_zip));
		}
		if ($this->country) {
			$address->push(trim($this->country));
		}

		return $address->implode(', ');
	}

	/**
	 *
	 */
	public function getDesiredEventsRawAttribute()
	{
		return implode(', ', $this->desired_events);	
	}

	/**
	 *
	 */
	public function setDesiredEventsRawAttribute($value)
	{
		return $this->desired_events = explode(',', $value);
	}

	/**
     * Route notifications for the mail channel.
     *
     * @param  \Illuminate\Notifications\Notification  $notification
     * @return array|string
     */
    public function routeNotificationForMail($notification)
    {
        // Return email address and name...
        return [$this->email_1 => $this->name];
    }

	/**
     * Specifies the user's FCM tokens
     *
     * @return string|array
     */
    public function routeNotificationForFcm()
    {
		return $this->fcmClientTokens->pluck('token')->toArray();
    }

	/**
     * The channels the user receives notification broadcasts on.
     *
     * @return string
     */
    public function receivesBroadcastNotificationsOn()
    {
        return 'platform-user.' . $this->user_code;
    }

	/**
     * @param string $user_code
     */
	public static function getByUserCode($value)
    {
    	return self::where('user_code', $value)->first();
    }
}

resources/views/partials/cards/forms/inventory_details.blade.php
<div class="card bg-light w-100">
    <div class="card-header text-white bg-primary d-flex justify-content-between align-items-center p-1">
        <div>Ticket inventory details</div>
        {{--<button data-toggle="modal" data-target="#exampleModalLong" class="float-right btn btn-dark btn-sm">Notes: @if(!$inventory->thread) No @else Yes @endif</button>--}}
        @if ($inventory->notes)
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#noteModal">{{ 'Note: ' . $inventory->notes }}</button>
        @else
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#noteModal">No notes</button>
        @endif

    </div>
    <div class="card-body">
        <form method="POST" action="{{route('tickets.update',$inventory->id)}}">
            <input type="hidden" name="_method" value="PUT">
            <input type="hidden" id="notes" name="notes" value="{{ $inventory->notes }}">
            @csrf

            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label for="purchase_number">Transaction number</label>
                        <input type="text" class="form-control" id="purchase_number"  value="{{$inventory->purchase_number}}" readonly="yes">
                    </div>
                    <div class="col">
                        <label for="order_number">Order number</label>
                        <input type="text" class="form-control" id="order_number" name="order_number"  value="{{$inventory->order_number}}">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label for="event">Event title</label>
                        <input type="text" class="form-control" id="event" name="event"  value="{{$inventory->event}}">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <div class="row">
                            <div class="col">
                                <label for="event_genre">Event Genre</label>
                                <select class="form-control" id="event_genre" name="event_genre">
                                    <option selected   value="{{$inventory->event_genre}}">{{$inventory->event_genre}}</option>
                                    @foreach(EventGenreRepository::getActive() as $genre)
                                        @if($inventory->event_genre != $genre->genre)<option value="{{$genre->genre}}">{{$genre->genre}}</option> @endif
                                    @endforeach
                                </select>
                            </div>
                            <div class="col">
                                <label for="arena">Arena</label>
                                <input type="text" class="form-control" id="arena" name="arena"  value="{{$inventory->arena}}" >
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label for="type_of_ticket">Type of ticket</label>

                        <select class="form-control" id="type_of_ticket" name="type_of_ticket">
                            <option  value="{{$inventory->type_of_ticket}}">{{$inventory->type_of_ticket}}</option>

                            @foreach(TicketTypeRepository::getActive() as $ticket_type)

                                @if($inventory->type_of_ticket != $ticket_type->tickettype)
                                    <option  value="{{$ticket_type->tickettype}}">{{$ticket_type->tickettype}}</option>
                                @endif

                            @endforeach
                        </select>
                    </div>
                    <div class="col">
                        <label for="country">Country</label>
                        <input type="text" class="form-control" id="country" name="country"  value="{{$inventory->country}}">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <div class="row">
                            <div class="col">
                                <label for="time_of_event">Site Purchased</label>
                                <input  class="form-control" id="site_purchased"  name="site_purchased" value="{{$inventory->site_purchased}}" >
                            </div>
                            <div class="col">
                                <label for="restrictions">Restrictions</label>
                                <input  class="form-control" id="restrictions"  name="restrictions" value="{{$inventory->restrictions ?? 'N/A'}}" >
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row">
                            <div class="col">
                                <label for="event_date">Event date: {{Carbon\Carbon::parse($inventory->event_date)->isoFormat('ddd')}} {{$inventory->event_date->format('d/m/Y')}}</label>
                                <input type="date" class="form-control col-12" id="event_date" name="event_date"  value="{{$inventory->event_date->format('Y-m-d')}}">
                            </div>
                            <div class="col">
                                <label for="time_of_event">Start Time</label>
                                <input type="time" class="form-control col-12" id="time_of_event"  name="time_of_event" value="{{$inventory->time_of_event}}" >
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label for="referral_1">Referral 1</label>
                        <input class="form-control" id="referral_1"  name="referral_1" value="{{ $inventory->referral_1 }}">
                    </div>
                    <div class="col">
                        <label for="referral_2">Referral 2</label>
                        <input class="form-control" id="referral_2"  name="referral_2" value="{{ $inventory->referral_2 }}">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label for="listed">Listed</label>
                        <input class="form-control" id="listed"  name="listed" value="{{ $inventory->listed }}">
                    </div>
                    <div class="col">
                        <label for="origin_status">Origin status</label>
                        <input class="form-control" id="origin_status"  name="origin_status" value="{{ $inventory->origin_status }}">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label for="selling_rate">Selling rate</label>
                        <input class="form-control" id="selling_rate"  name="selling_rate" value="{{ $inventory->selling_rate }}">
                    </div>
                    <div class="col">
                        <label for="paid_amount">Paid amount</label>
                        <input class="form-control" id="paid_amount"  name="paid_amount" value="{{ $inventory->paid_amount }}">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="row align-items-end">
                    <div class="col">
                        <button type="submit" class="btn px-4 btn-primary float-right">update details</button>
                    </div>
                </div>
            </div>

        </form>
    </div>
</div>

<!-- Modal -->
<div class="modal fade modal-down" id="noteModal" tabindex="-1" role="dialog" aria-labelledby="noteModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="noteModalTitle">Notes  - {{$inventory->purchase_number}}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col">
                        <label for="modal_notes">Ticket Note</label>
                        <input class="form-control" id="modal_notes" value="{{ $inventory->notes }}">
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" onclick="closeNoteModal()">Close</button>
                <button type="button" class="btn btn-primary" onclick="applyNoteModal({{$inventory->id}})">Apply</button>
            </div>
        </div>
    </div>
</div>

<script>
    $('#noteModal').on('shown.bs.modal', () => {
        // set focus
        $('#modal_notes').focus()
        toggleDetailModal();
    });

    $('#noteModal').on('hidden.bs.modal', function () {
        toggleDetailModal();
    });

    function applyNoteModal(inventory_id){
        var notesVal = $('#modal_notes').val()
        // change note
        $('#notes').val($('#modal_notes').val())
        $('button[data-target="#noteModal"]')
            .text('Note: ' + notesVal)
            .addClass('btn-danger')
        $('#noteModal').modal('hide')

        $.get('/api/ticketInfo/inventoryNotesTicketUpdate/'+inventory_id+'/'+notesVal).then((response) =>{
        })
    };

    function closeNoteModal(){
        $('#noteModal').modal('hide');
    }

    function toggleDetailModal(){
        $('#detailsModal').toggleClass('modal-down');
        $('body').toggleClass('modal-open');
    }
</script>

resources/views/partials/cards/forms/payment_details.blade.php
<div class="card w-100">
    <div class="card-header">Payment details</div>
    <div class="card-body">
        @if ($payment->id)
            <form method="post" action="{{ route('finances.payments.update', ['id' => $payment->id]) }}" autocomplete="off">
                @method('PUT')
        @else
            <form method="post" action="{{ route('finances.payments.create') }}" autocomplete="off">
        @endif
            @csrf
            <div class="row">

                <div class="form-group col-sm-2">
                    <label for="vat">Amount including VAT</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <div class="input-group-text">£</div>
                        </div>
                        <input type="number" step="0.01" class="form-control" id="amount_incl_vat" name="amount_incl_vat"
                            value="{{ old('amount_incl_vat', $payment->amount_incl_vat) }}">
                    </div>
                </div>

                <div class="form-group col-sm-8">
                    <label for="user_id">User</label>
                    <select class="form-control platform-user-id" id="user_id" name="user_id">
                        @foreach($platformUsers as $platformUser)
                            <option value="{{ $platformUser->id }}"
                                @if($platformUser->id == $payment->user_id) selected @endif>
                                {{ $platformUser->full_name_with_code }}
                            </option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group col-sm-2">
                    <label for="date">Date</label>
                    <input class="form-control datepicker" id="date" name="date"
                        value="{{ old('date', $payment->date->format('Y-m-d')) }}">
                </div>

                <div class="form-group col-sm-12">
                    <label for="notes">Notes</label>
                    <input class="form-control" id="notes" name="notes"
                        value="{{ old('notes', $payment->notes) }}">
                </div>

            </div>

            <button type="submit" class="btn btn-primary float-right">
                @if($payment->id) Update @else Create @endif
            </button>
        </form>
   </div>
</div>

resources/views/partials/cards/forms/sold_details.blade.php
<div class="card bg-light w-100">

    <div class="card-header   {{ $soldTicket->is_paid == 'Y' ? 'bg-success':'bg-danger' }} ">
        <h6 class="text-white">Sold information : <span class="float-right"> Paid ? =  {{ $soldTicket->is_paid == 'Y' ? 'YES':'NO' }}  </span> </h6>
    </div>

    <div class="card-body">
        <form method="POST" action="{{route('delivered.update',$soldTicket->id)}}">
            <input type="hidden" name="_method" value="PUT">
            @csrf
            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label for="purchase_number">Sold Ref</label>
                        <input type="text" class="form-control" id="sale_id_ref" name="sale_id_ref" value="{{$soldTicket->sale_id_ref}}">
                    </div>                    
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label for="ordernumber">Site  Sold</label>
                        <input type="text" class="form-control" id="" name="site_sold" value="{{$soldTicket->site_sold}}">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <label for="event">Sold Date</label>
                        <input type="text" class="form-control" id="event" name="sold_date" value="{{$soldTicket->sold_date}}">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <div class="row">
                            <div class="col">
                                <label for="seats">Seats</label>
                                <input type="text" class="form-control" id="seats" name="seats"  value="{{$soldTicket->seats}}" >
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col">
                        <div class="row">
                            <div class="col">
                                <label for="Arena">Ticket Qty Price</label>
                                <input type="text" class="form-control" id="Arena" name="ticket_qty"  value="{{$soldTicket->ticket_qty}}" >
                            </div>
                            <div class="col">
                                <label for="Arena">Sell Price</label>
                                <input type="text" class="form-control" id="Arena" name="sell_price"  value="{{$soldTicket->sell_price}}" >
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary float-right">update details</button>
        </form>
    </div>
</div>